# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "MyApp"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

views: "views"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
template: "handlebars"

# session engine
session: "YAML"
 
engines:
  session:
    YAML:
      session_dir: "tmp/sessions"
      cookie_name: "sessid"
      cookie_duration: 3600
      is_secure: 1
      is_http_only: 1

plugins:
  FlashNote:
    queue:   "single"
    dequeue: "when_used"